### ISSUE TITLE
The Chamfer Distance loss is still calculated like Neural Pull?

### ISSUE THREAD

**Issue by zhanghm1995** [junshengzhou/CAP-UDF#1]
Hi, thanks for sharing the code.

In your paper, you mentioned you "look for the surface point pi in P which is the closest to zi and minimize the distance between zi and pi".

It means we need to find the nearest point after moving the query points, but in your [code](https://github.com/junshengzhou/CAP-UDF/blob/67acab54ee812c2a7cdeecc5fd311f725e8897d8/run.py#L133), I found you still use the nearest point found in the original query points, just similar with the Neural Pull did.

I am not sure whether I misunderstand.

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest. Actually the difference lies in the calculation way of L1 and Chamfer Distance. The L1 loss force each query point to move to the unique point on P. (e.g. `[a->A],[b->B],[c->C]`. However, Chamfer Distance Loss is computed to minimize the distance between `[a,b,c] and [A,B,C]`, where the consistency can be guaranteed since if moved `a'` is closer to `B or C`,  the loss can also descend. Please refer to Sec3.2 of our paper for more details and analysis.

For implementation, we use the same data preparation as Neural-Pull. The `points` here in calculating loss is actually a set of points sampled from raw point cloud P, which is practically equivalent to P in implementation.

**Comment by zhanghm1995** [comment]
Thank you for your reply.
I wonder why the L1 loss for the Neural Pull works well by just forcing the moved query points to be closer to the corresponding points in surface points. Is it because of the difference between UDF and SDF predictions? 

From my perspective, if we use the L1 loss like Neural Pull, we can force the UDF to obtain more accurate gradients. And in Figure 3 of Sec3.2, the points on the surface are so sparse that the query points seem to find some conflict optimization direction, does the dense surface points could alleviate the consistency issue?

**Comment by junshengzhou** [comment]
Hi,
Yes, it is more difficult for designing a proper optimization target for UDF than SDF, since SDF only focus on learning a watertight shape, while UDF can be used in reconstructing shapes and scenes with arbitrary architecture where the optimization target used in Neural-Pull fails in many complex situation.

The L1 loss can not guarantee the consistency of fields as we discussed in the paper, but if the point cloud is dense enough, I believe this issue can be partly alleviated. However, the point cloud is always a  discrete approximation of the surface and it is not possible for achieving a highly dense raw point cloud in the real world situation.

**Comment by junshengzhou** [comment]
I'm closing this issue due to its inactivity. However, please feel free to reopen it if your problem persists.
